name: login_screen_homework
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  botton_nav_bar: ^1.0.2
  curved_navigation_bar: ^1.0.3
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^3.5.0
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.1
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.4
  http: ^1.1.0
  lottie: ^2.4.0
  image_picker: ^1.0.1
  modal_bottom_sheet: ^2.1.2
  zoom_tap_animation: ^1.1.0
  flutter_carousel_slider: ^1.1.0
  shimmer: ^3.0.0
  provider: ^6.0.5
  shared_preferences: ^2.0.0
  change_app_package_name: ^1.1.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  google_maps_flutter: ^2.4.0
  fluttertoast: ^8.0.7
  wtf_sliding_sheet: ^1.1.0
  location: ^5.0.0
  geocoding: ^2.1.0
  dio: ^5.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.6




flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/


  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Medium.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
          style: italic